const CHANNELS = Object.freeze({
  APP_GET_STATE: "app:getState",
  APP_SET_STATE: "app:setState",
  SHELL_OPEN: "shell:open",
  CHAT_LIST: "chat:list",
  CHAT_GET_MESSAGES: "chat:getMessages",
  CHAT_GET_OR_CREATE_BY_CONTACT: "chat:getOrCreateByContact",
  CHAT_APPEND_MESSAGE: "chat:appendMessage",
  CHAT_UPDATE_MESSAGE: "chat:updateMessage",
  CHAT_MESSAGE_APPENDED: "chat:message_appended",
  CONTACT_LIST: "contact:list",
  CONTACT_CREATE_BOT_FROM_TEMPLATE: "contact:createBotFromTemplate",
  WORKSPACE_GET_TREE: "workspace:getTree",
  WORKSPACE_CREATE: "workspace:create",
  WORKSPACE_RENAME: "workspace:rename",
  WORKSPACE_DELETE: "workspace:delete",
  WORKSPACE_READ_FILE: "workspace:readFile",
  WORKSPACE_WRITE_FILE: "workspace:writeFile",
  SETTINGS_GET_ASSISTANT_CONFIG: "settings:getAssistantConfig",
  SETTINGS_GET_MODEL_API_KEY: "settings:getModelApiKey",
  SETTINGS_SAVE_ASSISTANT_CONFIG: "settings:saveAssistantConfig",
  SETTINGS_UPLOAD_AVATAR: "settings:uploadAvatar",
  SETTINGS_SELECT_WORKPLACE_DIRECTORY: "settings:selectWorkplaceDirectory",
  SETTINGS_READ_IMAGE_DATA_URL: "settings:readImageDataUrl",
  SETTINGS_LIST_AVAILABLE_SKILLS: "settings:listAvailableSkills",
  SETTINGS_GET_SKILL_ENV: "settings:getSkillEnv",
  SETTINGS_SAVE_SKILL_ENV: "settings:saveSkillEnv",
  MEMORY_READ: "memory:read",
  MEMORY_WRITE: "memory:write",
  AGENT_INIT: "agent:init",
  AGENT_SET_MODEL: "agent:setModel",
  AGENT_PROMPT: "agent:prompt",
  AGENT_ABORT: "agent:abort",
  AGENT_EVENT: "agent:event",
  AGENT_EVENT_ERROR: "agent:eventError",
  ATTACHMENT_SAVE: "attachment:save",
  SYNC_PENDING_MESSAGES: "sync:pendingMessages",
  CHANNEL_LIST_CONFIGS: "channel:listConfigs",
  CHANNEL_SAVE_CONFIG: "channel:saveConfig",
  CHANNEL_DELETE_CONFIG: "channel:deleteConfig",
  CONTACT_GET_DEFAULT_BOT_ID: "contact:getDefaultBotId",
  SCHEDULED_TASKS_LIST: "scheduledTasks:list",
  SCHEDULED_TASKS_CREATE: "scheduledTasks:create",
  SCHEDULED_TASKS_UPDATE: "scheduledTasks:update",
  SCHEDULED_TASKS_DELETE: "scheduledTasks:delete",
  STORYBOARD_LIST: "storyboard:list",
  STORYBOARD_GET: "storyboard:get",
  STORYBOARD_CREATE: "storyboard:create",
  STORYBOARD_UPDATE: "storyboard:update",
  STORYBOARD_GET_ASSET_URL: "storyboard:getAssetUrl",
  STORYBOARD_SET_ACTIVE: "storyboard:setActive",
  STORYBOARD_GENERATE_IMAGE: "storyboard:generateImage",
  STORYBOARD_GENERATE_VIDEO: "storyboard:generateVideo",
  STORYBOARD_DELETE_RESOURCE: "storyboard:deleteResource",
  STORYBOARD_DELETE_GENERATION: "storyboard:deleteGeneration",
  STORYBOARD_ADD_RESOURCE: "storyboard:addResource",
  STORYBOARD_UPLOAD_LOCAL_ASSET: "storyboard:uploadLocalAsset",
  STORYBOARD_AGENT_CREATE: "storyboard:agentCreate",
  STORYBOARD_DELETE_PROJECT: "storyboard:deleteProject",
});

module.exports = {
  CHANNELS,
};
